---
# file: common/tasks/main.yml
# name: Common Configuration Playbook
- name: Changing SSH Options for GitHub
  command: echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> /root/.ssh/config

- name: Starting Docker
  service:
    name: docker
    state: started

- name: Add deploy user
  user:
    name: "{{ deploy_user_name }}" 
    password: "{{ deploy_user_password }}" 
    shell: "{{ deploy_user_shell }}"

- name: Add deploy user to sudoers
  lineinfile: 
    dest: /etc/sudoers
    regexp: "{{ deploy_user_name }} ALL"
    line: "{{ deploy_user_name }} ALL=(ALL) ALL"
    state: present
