---
# file: roles/nagios/install/group_vars/all.yml
# name: Nagios options
nagios_username: uradmin
nagios_password: Nothing2020!
nagios_create_guest_user: true
nagios_ro_username: gtfoh
nagios_ro_password: 1298431fp41f
nagios_http_port: 80
nagios_https_port: 443
admin_name_01: uradmin
# change this to your email address if you want notifications
admin_email_01: mrjvazquez@gmail.com
### NRPE variables ###
nrpe_tcp_port: 5666
warning_proc: 900
critical_proc: 1000
warning_users: 15
critical_users: 30
### ELK options ###
# if you use my ELK playbook you'll need this for HTTP checks
# https://github.com/sadsfae/ansible-elk
kibana_user: uradmin
kibana_password: Nothing2020!
