---
# file: {{ playbook_dir }}/roles/lin-fail2ban/tasks/main.yml
# name: Fail2Ban Role

- name: Install fail2ban
  apt: pkg=fail2ban state=installed update-cache=yes
  register: fail2ban_install
  tags:
    apt

- name: Install UFW ban action
  copy:
    src: ufw.ssh.conf
    dest: /etc/fail2ban/action.d/ufw.ssh.conf
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: Install config
  template: src=jail.local.j2 dest=/etc/fail2ban/jail.local
  notify:
    reload fail2ban

- name: Ensure Fail2Ban is running and enabled on boot.
  service: name=fail2ban state=started enabled=yes
