---
# file: stage-miner.yml
# name: Master Miner Playbook

# This is the main Miner playbook that will install all required components
# to UR miners specified in the group_vars/miners.yml file.
#
# All roles are designed to be idempotent.

- name: Load Variables
  hosts: miners
  vars_files:
    - group_vars/secrets.yml
    - group_vars/deployment.yml

- name: Common Linux Configuration 
  vars_files:
    - group_vars/secrets.yml
  hosts: miners
  roles:
    - lin-common
    - lin-ufw
    - lin-fail2ban

- name: UR Technology Configuration
  hosts: miners
  vars_files:
    - group_vars/secrets.yml
  roles:
   - ur-common
   - ur-gur

