---
# file: testing.yml
# name: Experimental Testing Playbook

  - include_vars: "group_vars/testing.yml"

  - include: test-bootnode.yml
    tags: test-bootnode
    when: testing
          and ur_deploy_test_bootnode

  - include: test-explorer.yml
    tags: test-explorer
    when: testing
          and ur_deploy_test_explorer

  - include: test-queue.yml
    tags: test-queue
    when: testing
          and ur_deploy_test_queue

  - include: test-relay.yml
    tags: test-relay
    when: testing
          and ur_deploy_test_relay
