---
# file: testing.yml
# name: Experimental Testing Playbook

- name: New Deployment Launch
  hosts: localhost
  roles:
    - ur-testing
  vars_files:
    - group_vars/secrets.yml

- name: Assign Floating IPs to New Deployment
  hosts: localhost
  tasks:
    - include: roles/ur-testing/tasks/floating-ip.yml
  vars_files:
    - group_vars/secrets.yml

- name: Common Deployment
  hosts: all:!monitor:!automator:!localhost
  strategy: debug
  roles:
    - ur-common

- name: Droplet Deployment Bootnodes
  hosts: tor1-bootnode:!localhost
  roles:
    - ur-gur
    - ur-bootnode

- name: Explorer Droplet Deployment
  hosts: tor1-explorer:!localhost
  roles:
    - ur-explorer

- name: Droplet Deployment Queue
  hosts: tor1-queue:!localhost
  roles:
    - ur-gur
    - ur-queue

- name: Relay Droplet Deployment
  hosts: tor1-relay:!localhost
  roles:
    - ur-gur
    - ur-relay
