---
# file: {{ playbook_dir }}/roles/lin-common/defaults/main.yml
# name: Default Linux Variables 

common_apt_packages:
        - apt-transport-https
        - ca-certificates
        - "linux-image-extra-{{ ansible_kernel }}"
        - linux-image-extra-virtual
        - docker-engine

deploy_user_name: deploy
deploy_user_workdir: /home/deploy
deploy_user_groups:
  - sudo
  - deploy
deploy_user_shell: /bin/bash
