---
# file: roles/common/tasks/main.yml
# name: Gur Playbook for Ubuntu
- name: Update Repository Cache
  apt:
    update_cache: yes
    dpkg_options: no-install-recommends apt-utils

- name: Install List of Packages
  action: apt pkg={{ item }} state=installed
  with_items:
     - build-essential
     - dnsutils
     - git
     - golang
     - inetutils-ping
     - libgmp3-dev

- name: Create UR Directories
  action: file path={{ item }} state=directory mode=0775
  with_items:
     - /root/ur_data
     - .ethash

- name: Opens UFW TCP Port 9595
  action: ufw
    rule=allow
    port=9595
    proto=tcp

- name: Opens UFW TCP Port 9595
  action: ufw
    rule=allow
    port=19595
    proto=tcp

- name: Opens UFW UDP ports
  ufw:
    rule=allow
    port=19595
    proto=udp
