---
# file: roles/common/defaults/main.yml
# name: Common Linux Variables 

ur_deploy_user_name: deploy
ur_deploy_user_password: {{ ur_deploy_user_password }}

ur_common_apt_packages_list:
  - transport-http
  - ca-certificates
  - linux-image-extra-$(uname -r)
  - linux-image-extra-virtual
  - docker-engine


