---
# Role defaults

do_api_token: "{{ lookup( 'env','DO_API_TOKEN' ) }}"
do_ssh_key_id: "{{ ur_ssh_key.ssh_key.id }}"
do_ssh_pub_key: "{{ lookup('file', do_ssh_key_file ) }}"
do_ssh_key_state: present
do_generate_ssh_key: yes
do_ssh_key_name: ur_ssh_key
do_ssh_key_file: ~/.ssh/UR-ssh-key_rsa
