---
# file: roles/deploy-test/tasks/floating-ip.yml
# name: Assign Floating IPs to Test Deployment

  - copy:
      src: "{{ playbook_dir }}/roles/ur-testing/files/assign-floating-ips.sh"
      dest: /root/assign-floating-ips.sh
      owner: root
      group: root
      mode: "u=rwx,g=rx,o=rx"

  - name: Export the API Token
    shell: "export DO_API_TOKEN={{ do_api_token }} | /root/assign-floating-ips.sh"
    args:
      executable: /bin/bash
