---
# file: roles/deploy-test/defaults/main.yml
# name: Test Deployment Defaults

do_ssh_key_state: yes
do_generate_ssh_key: yes
do_ssh_key_name: new_ssh_key
do_ssh_key_file: ~/.ssh/new-ssh-key
do_ssh_pub_key: "{{ lookup('file', '~/.ssh/new-ssh-key.pub') }}"
do_ssh_key_id: "{{ new_ssh_key.ssh_key.id }}"
do_backups_enabled: no
do_image_id: 21543639
do_private_networking: yes
do_region_id: tor1
do_size_id: 512mb
do_unique_name: yes
do_virtio: yes
do_wait: yes
do_wait_timeout: 300
