---
# file: {{ playbook_dir }}/roles/do-inventory/tasks/main.yml
# Add Droplets to Inventory

- name: Add Droplet to Inventory
  add_host: >
    name="{{ item }}"
    group="{{ ur_inventory_groups }}"
    ansible_ssh_host={{ item.droplet.ip_address }}
    ansible_ssh_user="{{ do_ssh_user }}"
    ansible_ssh_private_key_file="{{ do_ssh_key_file }}"
  with_items: droplets
 
