---
# file: {{ playbook_dir }}/roles/do-copy-ssh-key/tasks/main.yml
# name: Copy SSH Key to Digital Ocean
- name: Copy SSH key to Digital Ocean
  digital_ocean: >
    state="{{ do_ssh_key_state }}"
    command="ssh"
    name="{{ do_ssh_key_name }}"
    ssh_pub_key="{{ do_ssh_pub_key }}"
    api_token="{{ do_api_token }}"
  register: new_ssh_key
