---
# file: {{ ansible_playbook }}/roles/lin-ufw/tasks/main.yml
# name: Sets UFW rules

- name: Allow OpenSSH
  ufw:
    rule: allow
    name: OpenSSH
  with_items:
    droplets

- name: Install Gur Definition
  copy:
    src: gur.conf
    dest: /etc/ufw/applications.d/gur.conf
    owner: root
    group: root
    mode: 0644
    backup: no
  with_items:
    droplets

- name: Update UFW Definitions
  command: ufw app update gur
  with_items:
    droplets

- name: Get Gur Info
  command: ufw app info gur
  with_items:
    droplets

- name: Allow Gur
  ufw:
    rule: allow
    name: gur
  with_items:
    droplets

- name: Ensure UFW is running and enabled on boot
  service: name=ufw state=started enabled=yes
  notify: 
    reload ufw
  with_items:
    droplets
